### ISSUE TITLE
Error when running on windows 10 

### ISSUE THREAD

**Issue by jakes670** [TKCERT/pfFocus#1]
### Issue summary

Get errors when running 

C:\pfFocus-master>format.py -i c:\pfFocus-master\config-firewall.123-20170620171532.xml -o c:\pfFocus-master\kk -f yaml

### Steps to reproduce
1.  RUN CMD as admin
2.  run C:\pfFocus-master>format.py -i c:\pfFocus-master\config-firewall.123-20170620171532.xml -o c:\pfFocus-master\kk -f yaml

### Expected result
Should get formated output

### Actual result

C:\pfFocus-master>format.py -i c:\pfFocus-master\config-firewall.123-20170620171532.xml -o c:\pfFocus-master\kk -f yaml
⚋ Parsing "c:\pfFocus-master\config-firewall.123-20170620171532.xml" ...
Traceback (most recent call last):
  File "C:\pfFocus-master\format.py", line 73, in <module>
    main()
  File "C:\pfFocus-master\format.py", line 66, in main
    step_parse(args, doc)
  File "C:\pfFocus-master\format.py", line 39, in step_parse
    parse_pfsense(args.input_path, doc)
  File "C:\pfFocus-master\parse.py", line 75, in parse_pfsense
    parse(input_file, handler)
  File "C:\Python\Python36-32\lib\site-packages\defusedxml-0.5.0-py3.6.egg\defusedxml\sax.py", line 26, in parse
  File "C:\Python\Python36-32\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Python\Python36-32\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Python\Python36-32\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "..\Modules\pyexpat.c", line 282, in CharacterData
  File "C:\pfFocus-master\parse.py", line 50, in characters
    cur(stack_chars.getvalue())
  File "C:\pfFocus-master\pfsense.py", line 50, in __call__
    self.integer = int(content)
ValueError: invalid literal for int() with base 10: '1024:65535'

__________________________________________________________________

C:\pfFocus-master>parse.py config-firewall.123-20170620171532.xml
Traceback (most recent call last):
  File "C:\pfFocus-master\parse.py", line 89, in <module>
    main()
  File "C:\pfFocus-master\parse.py", line 85, in main
    parse_pfsense(args.input_path, doc)
  File "C:\pfFocus-master\parse.py", line 75, in parse_pfsense
    parse(input_file, handler)
  File "C:\Python\Python36-32\lib\site-packages\defusedxml-0.5.0-py3.6.egg\defusedxml\sax.py", line 26, in parse
  File "C:\Python\Python36-32\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Python\Python36-32\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Python\Python36-32\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "..\Modules\pyexpat.c", line 282, in CharacterData
  File "C:\pfFocus-master\parse.py", line 50, in characters
    cur(stack_chars.getvalue())
  File "C:\pfFocus-master\pfsense.py", line 50, in __call__
    self.integer = int(content)
ValueError: invalid literal for int() with base 10: '1024:65535'

### Version and method
 - Windows 10 64 bit
 - Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
 - defusedxml-0.5.0
- PyYAML-3.12

**Comment by mback2k** [comment]
Could you please search your xml export for the string "1024:65535" and tell me in which section it occurs? It looks like a port range that pfFocus tries to handle like a single integer.

**Comment by jakes670** [comment]
Sorry forgot to mention PFsense version 2.3.4-RELEASE (i386)

I found this

<rule>
                                                                <source>
                                                                                <network>127.0.0.0/8</network>
                                                                </source>
                                                                <dstport></dstport>
                                                                <descr><![CDATA[Auto created rule for localhost to WAN]]></descr>
                                                                <target></target>
                                                                <interface>wan</interface>
                                                                <destination>
                                                                                <any></any>
                                                                </destination>
                                                                <natport>1024:65535</natport>
                                                                <created>
                                                                                <time>1384959804</time>
                                                                                <username>Manual Outbound NAT Switch</username>
                                                                </created>
                                                </rule>


I removed that section error still thee just a little bit different

C:\pfFocus-master>parse.py config.xml
Traceback (most recent call last):
  File "C:\pfFocus-master\parse.py", line 89, in <module>
    main()
  File "C:\pfFocus-master\parse.py", line 86, in main
    pprint(doc)
  File "C:\Python\Python36-32\lib\pprint.py", line 53, in pprint
    printer.pprint(object)
  File "C:\Python\Python36-32\lib\pprint.py", line 139, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "C:\Python\Python36-32\lib\pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "C:\Python\Python36-32\lib\pprint.py", line 393, in _repr
    self._depth, level)
  File "C:\Python\Python36-32\lib\pprint.py", line 405, in format
    return _safe_repr(object, context, maxlevels, level)
  File "C:\Python\Python36-32\lib\pprint.py", line 555, in _safe_repr
    rep = repr(object)
  File "C:\pfFocus-master\pfsense.py", line 20, in __repr__
    return pformat(self.data)
  File "C:\pfFocus-master\pfsense.py", line 14, in __getattr__
    return super().__getattribute__(name)
  File "C:\pfFocus-master\util.py", line 13, in data
    data[key] = value.data
  File "C:\pfFocus-master\pfsense.py", line 14, in __getattr__
    return super().__getattribute__(name)
  File "C:\pfFocus-master\util.py", line 13, in data
    data[key] = value.data
  File "C:\pfFocus-master\pfsense.py", line 14, in __getattr__
    return super().__getattribute__(name)
  File "C:\pfFocus-master\util.py", line 13, in data
    data[key] = value.data
  File "C:\pfFocus-master\pfsense.py", line 14, in __getattr__
    return super().__getattribute__(name)
  File "C:\pfFocus-master\pfsense.py", line 131, in data
    for iface_name in data.split(','):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by mback2k** [comment]
Could you please try the latest version? Thanks.

**Comment by mback2k** [comment]
According to Twitter message: "New version on github working. Thanks".
