### ISSUE TITLE
format.py is unable to parse rule when alias name is used for ports

### ISSUE THREAD

**Issue by kendokan** [TKCERT/pfFocus#4]
```
$ ./format.py -i ~/Desktop/config.xml -f md -o ~/Desktop/config.md
\u268b Parsing "C:/Users/x/Desktop/config.xml" ...
Traceback (most recent call last):
  File "./format.py", line 73, in <module>
    main()
  File "./format.py", line 66, in main
    step_parse(args, doc)
  File "./format.py", line 39, in step_parse
    parse_pfsense(args.input_path, doc)
  File "C:\Users\x\Projects\pfFocus\parse.py", line 75, in parse_pfsense
    parse(input_file, handler)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36-32\lib\site-packages\defusedxml\sax.py", line 26, in parse
    parser.parse(source)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36-32\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36-32\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36-32\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "..\Modules\pyexpat.c", line 282, in CharacterData
  File "C:\Users\x\Projects\pfFocus\parse.py", line 50, in characters
    cur(stack_chars.getvalue())
  File "C:\Users\x\Projects\pfFocus\pfsense.py", line 51, in __call__
    self.integer = int(content)
ValueError: invalid literal for int() with base 10: 'Photon_External'

```

Relevant section of config.xml:

```
		<rule>
			<source>
				<any></any>
			</source>
			<destination>
				<network>wanip</network>
				<port>Photon_External</port>
```

**Comment by kendokan** [comment]
Pull request submitted.
